version: "3"
services:
  web:
    build:
      context: .
      dockerfile: dockers/python/Dockerfile
    depends_on:
      - "database"
      - "redis"

  workerserver:
    build:
      context: .
      dockerfile: dockers/python/Dockerfile
    command: "python manage.py runworker confirmation_email"
    depends_on:
      - "database"
      - "redis"
    env_file:
      .env

  database:
    image: "postgres:9.6"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"

volumes:
  pgdata:
