version: "3"
services:

  nginx:
    build: ./dockers/nginx
    ports:
      - 80:80
    depends_on:
      - "web"

  web:
    command: "daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    environment:
      DEBUG: "false"
      DJANGO_SETTINGS_MODULE: "config.settings.production"
    env_file:
      - .env
