version: "3"
services:
  web:
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      DEBUG: "true"
      SECRET_KEY: "development_key"
      DJANGO_SETTINGS_MODULE: "config.settings.development"
      DB_HOST: "database"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: ""

  workerserver:
    volumes:
      - .:/app
    environment:
      DEBUG: "true"
      SECRET_KEY: "development_key"
      DJANGO_SETTINGS_MODULE: "config.settings.development"
      DB_HOST: "database"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: ""
      DOMAIN: "http://localhost:8000"
