version: "3"
services:
  web:
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      DEBUG: "false"
      DJANGO_SETTINGS_MODULE: "config.settings.production"
    env_file:
      - .env
