version: "3"
services:
  web:
    command: "python manage.py test"
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: "config.settings.testing"
      DB_HOST: "database"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: ""
