version: "3"
services:

  pgadmin4:
    image: dpage/pgadmin4
    environment:
    - PGADMIN_DEFAULT_EMAIL=test@gmail.com
    - PGADMIN_DEFAULT_PASSWORD=qwerty
    ports:
    - "8001:80"
    depends_on:
    - "database"

  mail:
    image: djfarrelly/maildev
    ports:
      - "8002:80"
    depends_on:
      - "web"

  php-redis-admin:
    image: faktiva/php-redis-admin
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
    ports:
      - "8003:80"
    depends_on:
      - "redis"
