version: "3"
services:
  web:
    command: "daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      DEBUG: "false"
      DJANGO_SETTINGS_MODULE: "config.settings.production"
    env_file:
      - .env
