[tool.poetry]
name = "planeks-test"
version = "0.1.0"
description = ""
authors = ["Kirill Shitikov <shitikovkirillt@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
django = "^2.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
