# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:80/api/users/
Content-Type: application/json

{
  "email": "sh.kiruh2@gmail.com",
  "password": "test1"
}

###

POST http://localhost:8000/api/token/
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "test1"
}

###

POST http://localhost:8000/api/users/113/confirm-email/
Content-Type: application/json

{
  "token": "59z-a1c70132cea785e637a1"
}

###